[project]
name = "genesis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "genesis-world>=0.2.1",
    "rsl-rl-lib==2.2.4",
    "tensorboard>=2.19.0",
]
